set -g base-index 1
set -g history-limit 10000
set -g mouse on
set -g prefix \\
set -g set-clipboard off
set -g set-titles on
set -g status off
set -g status-right '#T'
setw -g mode-keys vi
setw -g pane-base-index 1

# Delete the not sane default keybindings
unbind %
unbind '"'
unbind C-b

# Allow copying to the X clipboard
bind -T copy-mode-vi MouseDragEnd1Pane \
	send-keys -X copy-pipe-no-clear 'xclip -se p -i'
bind -T copy-mode-vi C-c \
	send-keys -X copy-pipe-no-clear 'xclip -se c -i'
bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -se c -i'
bind -T copy-mode-vi v if-shell '[ #{selection_active} -eq 1 ]' {
	send-keys -X clear-selection
} {
	send-keys -X begin-selection
}

bind C-l send-keys -R \; clear-history
bind F1 set status
bind P paste-buffer
bind R source-file ~/.config/tmux/tmux.conf \; \
         display 'tmux.conf re-sourced!'
bind \\ send-prefix
bind h split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'
