#!/bin/sh

userdir() {
	path=$(xdg-user-dir "$1")
	if [ "$(dirname "$path")" = "$HOME" ]; then
		basename "$path"
	else
		echo "$path"
	fi
}

set -e

arch_dir=$(realpath "$(userdir DOWNLOAD)/archives")
prism_dir=~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/vanilla/minecraft
gpg_arch=$arch_dir/$USER.gpg
mc_arch=$arch_dir/minecraft.zip
tmp_arch=$USER.zip.tmp

for arg; do
	case $arg in
		-*) ;;
		*) arg=$(realpath "$arg") ;;
	esac
	set -- "$@" "$arg"
	shift
done

cd ~
mkdir -p "$arch_dir"

zip -q9r - "$(userdir DOCUMENTS)" "$@" > "$tmp_arch"
if [ -f ~/.pass ]; then
	gpg --no-symkey-cache --decrypt ~/.pass |
		gpg --no-symkey-cache --batch --yes --passphrase-fd 0 \
			--output "$gpg_arch" --symmetric "$tmp_arch"
	shred -u "$tmp_arch"
else
	mv "$tmp_arch" "$arch_dir/$USER.zip"
fi

if [ -d "$prism_dir" ]; then
	cd "$prism_dir"
	zip -q9r - saves screenshots servers.dat > "$mc_arch"
fi

cd "$arch_dir"
if [ -f md5sum.txt ]; then
	mv md5sum.txt md5sum.old.txt
fi

if [ -f "$gpg_arch" ]; then
	md5sum ./*.gpg ./*.zip > md5sum.txt
else
	md5sum ./*.zip > md5sum.txt
fi
