#!/bin/sh

exec vim -c 'syn off |
	colo default |
	set nornu |
	hi LineNr ctermfg=8 |
	hi Pmenu ctermbg=7 ctermfg=0 cterm=NONE |
	hi PmenuSel ctermbg=10 ctermfg=0 |
	hi PmenuThumb ctermbg=8 |
	hi PmenuSbar ctermbg=0 |
	hi Search ctermfg=0 |
	hi Visual ctermbg=0 cterm=inverse |
	hi TabLine ctermfg=7 ctermbg=0 |
	hi TabLineSel cterm=inverse |
	hi TabLineFill ctermfg=0' "$@"
