#!/bin/sh

set -e

history=~/.config/qalculate/qalc.history

if [ ! -f "$history" ]; then
	mkdir -p "$(dirname "$history")"
	echo 'x^2 = 64' > "$history"
fi

expression=$(tac < "$history" | dmenu -i -l 24 -p "calc" "$@")

result=$(qalc +u8 --terse -- "$expression")

echo "$expression" >> "$history"

echo "$result" | xclip -rmlastnl -selection clipboard

notify-send -u normal -- 'qalc' "$result"
