#!/bin/sh

if [ $# -eq 0 ]; then
	exec redshift -PO 2500 2>/dev/null
elif [ $# -ne 1 ]; then
	echo '?' >&2
	exit 1
fi

case $1 in
[1-9]*)	exec redshift -PO "$@" ;;
*)	exec redshift -x 2>/dev/null ;;
esac
