#!/bin/sh

set -e

trysudo() {
	if [ "$(id -u)" -eq 0 ] || ! command -v sudo >/dev/null; then
		"$@"
	else
		sudo -- "$@"
	fi
}

. /etc/os-release

distro=${ID_LIKE:-$ID}

case $distro in
*debian*)
	trysudo apt update
	trysudo apt -y upgrade
	;;
*)
	echo "Not supported" >&2
	exit 1
	;;
esac

if command -v flatpak >/dev/null; then
	printf 'Try to update flatpaks? [Y/n] '
	read opt
	case $opt in
		''|[Yy]*) flatpak update -y ;;
		*) exit ;;
	esac
fi
